### ISSUE TITLE
Add support for vhost-user

### ISSUE THREAD

**Issue by sboeuf** [intel/cloud-hypervisor#7]
This is a generic issue to globally track the work to support multiple vhost-user devices (backends).

Subtasks references:
- [x] vhost-user-net #8
- [x] vhost-user-fs #9
- [x] vhost-user-blk #130

**Comment by sboeuf** [comment]
This issue can be closed now.
